version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - tfg_network

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - tfg_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - tfg_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  tfg_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1400"

volumes:
  ollama_data: